dist: trusty
language: rust
cache: cargo
rust:
  - nightly-2019-06-18
env:
  - SETTLE_TIME=2000
script:
  - cargo check --all --all-targets
  - cargo test --all -- --test-threads=1
addons:
  apt:
    packages:
    - liblz4-dev
before_cache:
  - rm -rf /home/travis/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target/incremental
  - |
    cd $TRAVIS_BUILD_DIR/target
    PACKAGES=("noria" "noria-server" "common" "mir" "dataflow" "vote" "replay" "securecrp" "piazza" "hotsoup" "evict-o-rama" "extract_hotcrp_queries" "lobsters")
    for PACK in $PACKAGES ; do
        find -regextype posix-extended -maxdepth 3 -regex "./(debug|target)/deps/${PACK//"-"/"_"}-(\\d|\\w)+(\\.d)?" -print -delete
    done
    find -maxdepth 1 -type f -not -name ".*" -delete
