[workspace]
members = [
	"noria",
	"noria-server",
	"noria-benchmarks",
	"noria-benchmarks/lobsters",
	"noria-http",
]

[profile.release]
debug=true

[patch.'https://github.com/tower-rs/tower.git']
tower-balance = { path = '/home/gina/tower/tower-balance' }
tower-load = { path = '/home/gina/tower/tower-load' }

[patch.crates-io]
tower-buffer = { path = '/home/gina/tower/tower-buffer' }
